import { Text } from '@mantine/core';
import styles from '@/styles/Home.module.css';
import Tasks from './tasks';
import TaskInput from '@/components/task/taskInput';
import { useState } from 'react';
import api from '@/utils/api';
import Head from 'next/head';

const Main = ({ taskData }) => {
  const [tasks, setTasks] = useState(taskData);
  const [input, setInput] = useState('');
  const [isEdit, setIsEdit] = useState(false);

  // // creating new task
  const handleCreateNew = async () => {
    try {
      const result = await api.post('/task', { task: input });

      setTasks([...tasks, result.data]);
      setInput('');
    } catch (error) {
      console.error('API error:', error);
    }
  };

  // // handling deleting
  const handleDeleting = async (taskId) => {
    console.log('Deletin task is workings');

    try {
      const result = await api.delete(`/task/${taskId}`);

      setTasks(tasks.filter((item) => item._id !== taskId));
    } catch (error) {
      console.error(error);
      throw error;
    }
  };

  //
  const settingEditing = async (taskId) => {
    console.log('set edit workin ...');
    // getting praticular task and updating in edit task input feald
    try {
      const result = await api.get(`/task/${taskId}`);
      setInput(result.data.task);
    } catch (error) {
      console.error(error);
      throw error;
    }
  };

  // // handling editing
  const handleEditing = async () => {
    // after all operations

    try {
      const result = await api.put(`/task/${isEdit}`, { task: input });
      console.log('API response:', result);
      // const response = await api.get('/tasks');
      setTasks(result.data.data);
      setInput('');
    } catch (error) {
      console.error('API error:', error);
    }
    // // after all operations
    setIsEdit(false);
  };

  return (
    <>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main}>
        <div className="main_wrap">
          <div className={styles.crud_wrapper}>
            <Text size="g" weight={500} className>
              ToDo App
            </Text>
            {/* input task component */}
            <TaskInput
              setInput={setInput}
              handleCreateNew={handleCreateNew}
              input={input}
              isEdit={isEdit}
              setIsEdit={setIsEdit}
              handleEditing={handleEditing}
            />
            {tasks?.length !== 0 ? (
              <Tasks
                tasks={tasks}
                setIsEdit={setIsEdit}
                settingEditing={settingEditing}
                handleDeleting={handleDeleting}
              />
            ) : (
              <h1>Add some tasks..</h1>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

Main.getInitialProps = async () => {
  console.log('Making API call...');
  try {
    const result = await api.get('/tasks');
    console.log('API response:', result);
    if (result.data.length < 0) {
      return console.log('No Tasks');
    }
    return { taskData: result.data };
  } catch (error) {
    console.error('API error:', error);
  }
};

export default Main;
